name: CryptoApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

targets:
  CryptoApp:
    type: application
    platform: macOS
    sources:
      - path: CryptoApp
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.cryptoapp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
